{"name": "test_create_courier_existing_login_response_body", "status": "failed", "statusDetails": {"message": "AssertionError: assert 'Этот логин у...буйте другой.' == 'Этот логин уже используется'\n  - Этот логин уже используется\n  + Этот логин уже используется. Попробуйте другой.", "trace": "self = <tests.test_create_courier.TestCreateCourier object at 0x000002518E15BB90>\n\n    def test_create_courier_existing_login_response_body(self):\n        payload = DataForTests.existing_user\n        response = requests.post((Urls.main_site + ApiHandles.create_courier), data=payload).json()\n>       assert response[\"message\"] == \"Этот логин уже используется\"\nE       AssertionError: assert 'Этот логин у...буйте другой.' == 'Этот логин уже используется'\nE         - Этот логин уже используется\nE         + Этот логин уже используется. Попробуйте другой.\n\ntests\\test_create_courier.py:86: AssertionError"}, "start": 1701269538248, "stop": 1701269538796, "uuid": "b524174e-138a-4659-87dc-f49cecafd9ac", "historyId": "154c54e66713f1be4464da0f6b7dba38", "testCaseId": "154c54e66713f1be4464da0f6b7dba38", "fullName": "tests.test_create_courier.TestCreateCourier#test_create_courier_existing_login_response_body", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_create_courier"}, {"name": "subSuite", "value": "TestCreateCourier"}, {"name": "host", "value": "ARSENIY-PC"}, {"name": "thread", "value": "27404-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_create_courier"}]}