{"name": "test_accept_order_without_order_id", "status": "failed", "statusDetails": {"message": "AssertionError: assert 'Not Found.' == 'Недостаточно...ых для поиска'\n  - Недостаточно данных для поиска\n  + Not Found.", "trace": "self = <tests.test_accept_order.TestAcceptOrder object at 0x000002518E158850>\n\n    def test_accept_order_without_order_id(self):\n        order_id = helper.get_new_order_id_by_track()\n        response = requests.put(f'{Urls.main_site}{ApiHandles.accept_order}?courierId={DataForTests.existing_user_id}').json()\n>       assert response[\"message\"] == \"Недостаточно данных для поиска\"\nE       AssertionError: assert 'Not Found.' == 'Недостаточно...ых для поиска'\nE         - Недостаточно данных для поиска\nE         + Not Found.\n\ntests\\test_accept_order.py:27: AssertionError"}, "start": 1701269511284, "stop": 1701269513300, "uuid": "8e958fce-8964-4d11-b890-0d1a124b2803", "historyId": "af66eded73cf39e7112a84e826dffdfa", "testCaseId": "af66eded73cf39e7112a84e826dffdfa", "fullName": "tests.test_accept_order.TestAcceptOrder#test_accept_order_without_order_id", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_accept_order"}, {"name": "subSuite", "value": "TestAcceptOrder"}, {"name": "host", "value": "ARSENIY-PC"}, {"name": "thread", "value": "27404-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_accept_order"}]}