{"name": "test_create_courier_which_already_exist", "status": "failed", "statusDetails": {"message": "AssertionError: assert (409 == 409 and 'Этот логин у...буйте другой.' == 'Этот логин уже используется'\n +  where 409 = <Response [409]>.status_code\n  - Этот логин уже используется\n  + Этот логин уже используется. Попробуйте другой.)", "trace": "self = <tests.test_create_courier.TestCreateCourier object at 0x0000017BA9EC7310>\n\n    def test_create_courier_which_already_exist(self):\n        payload = DataForTests.existing_user\n        response = requests.post((Urls.main_site + ApiHandles.create_courier), data=payload)\n        print(response.json())\n>       assert response.status_code == 409 and response.json()[\"message\"] == \"Этот логин уже используется\"\nE       AssertionError: assert (409 == 409 and 'Этот логин у...буйте другой.' == 'Этот логин уже используется'\nE        +  where 409 = <Response [409]>.status_code\nE         - Этот логин уже используется\nE         + Этот логин уже используется. Попробуйте другой.)\n\ntests\\test_create_courier.py:29: AssertionError"}, "attachments": [{"name": "stdout", "source": "653ea2ad-83c0-4768-9e8b-3ef7e3ebc0f1-attachment.txt", "type": "text/plain"}], "start": 1701432361913, "stop": 1701432362421, "uuid": "5238e685-09de-4ecf-a8e4-414e02f41150", "historyId": "7dff711c9b2f3470955c286899756d71", "testCaseId": "7dff711c9b2f3470955c286899756d71", "fullName": "tests.test_create_courier.TestCreateCourier#test_create_courier_which_already_exist", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_create_courier"}, {"name": "subSuite", "value": "TestCreateCourier"}, {"name": "host", "value": "ARSENIY-PC"}, {"name": "thread", "value": "30136-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_create_courier"}]}